os: linux
dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libdbus-glib-1-dev

language: python
python: "3.4"

branches:
    only: master

matrix:
    allow_failures:
        - env: TASK=lint
    include:
        - env: TASK=lint
        - env: TASK=fmt-travis

script: make -f Makefile $TASK
